const techAgencyNames = [
    "CodeCrafters",
    "TechVisionary",
    "DataNexus",
    "ByteForge",
    "InnovaTech",
    "CodeWizardry",
    "DigitalFrontiers",
    "TechMinds",
    "NexGenTech",
    "CodeLaunch",
    "InfiniteLoop",
    "FutureTechSavvy",
    "TechJunction",
    "CodeSphere",
    "TechForge",
    "Innovatech",
    "DataPulse",
    "CodeSyndicate",
    "DigitalNest",
    "TechPioneers",
    "ByteGenius",
    "InnoSpark",
    "CodeImpact",
    "TechBlaze",
    "DataMinds",
    "CodeMatrix",
    "TechHive",
    "NexTechWave",
    "CodeBurst",
    "InnovaCode",
    "DataCrafters",
    "TechVortex",
    "CodeGenie",
    "DigitalHorizon",
    "TechStorm",
    "ByteCrafters",
    "InnoTechSolutions",
    "CodeWave",
    "TechSavants",
    "DataPioneers",
    "CodeVerse",
    "TechRevolution",
    "NexDataTech",
    "CodeLogic",
    "InnoVision",
    "DataSphere",
    "TechNest",
    "ByteForge",
    "CodeSavvy",
    "DigitalFrontiers",
    "TechMinds",
    "NexGenTech",
    "CodeLaunch",
    "InfiniteLoop",
    "FutureTechSavvy",
    "TechJunction",
    "CodeSphere",
    "TechForge",
    "Innovatech",
    "DataPulse",
    "CodeSyndicate",
    "DigitalNest",
    "TechPioneers",
    "ByteGenius",
    "InnoSpark",
    "CodeImpact",
    "TechBlaze",
    "DataMinds",
    "CodeMatrix",
    "TechHive",
    "NexTechWave",
    "CodeBurst",
    "InnovaCode",
    "DataCrafters",
    "TechVortex",
    "CodeGenie",
    "DigitalHorizon",
    "TechStorm",
    "ByteCrafters",
    "InnoTechSolutions",
    "CodeWave",
    "TechSavants",
    "DataPioneers",
    "CodeVerse",
    "TechRevolution",
    "NexDataTech",
    "CodeLogic",
    "InnoVision",
    "DataSphere",
    "TechNest",
    "ByteForge",
    "CodeSavvy",
    "DigitalFrontiers",
    "TechMinds",
    "NexGenTech",
    "CodeLaunch",
    "InfiniteLoop",
    "FutureTechSavvy",
    "TechJunction",
    "CodeSphere",
    "TechForge",
    "Innovatech",
    "DataPulse",
    "CodeSyndicate",
    "DigitalNest",
    "TechPioneers",
    "ByteGenius",
    "InnoSpark",
    "CodeImpact",
    "TechBlaze",
    "DataMinds",
    "CodeMatrix",
    "TechHive",
    "NexTechWave",
    "CodeBurst",
    "InnovaCode",
    "DataCrafters",
    "TechVortex",
    "CodeGenie",
    "DigitalHorizon",
    "TechStorm",
    "ByteCrafters",
    "InnoTechSolutions",
    "CodeWave",
    "TechSavants",
    "DataPioneers",
    "CodeVerse",
    "TechRevolution",
    "NexDataTech",
    "CodeLogic",
    "InnoVision",
    "DataSphere",
    "TechNest",
    "CodeCraft",
    "TechBeam",
    "DataPulse",
    "InnoWorks",
    "ByteHive",
    "TechGenesis",
    "CodeStream",
    "NexaTech",
    "DigitalEcho",
    "TechSpark",
    "CodeFusion",
    "InnoImpact",
    "DataMatrix",
    "TechSynergy",
    "ByteStorm",
    "CodeNest",
    "InnoLogic",
    "DataForge",
    "TechBlast",
    "ByteWave",
    "CodeVista",
    "InnoSphere",
    "DataPulse",
    "TechMatrix",
    "ByteSpark",
    "CodeInfinite",
    "InnoVerse",
    "DataStorm",
    "TechCraft",
    "ByteImpact",
    "CodeBlaze",
    "InnoBurst",
    "DataGenie",
    "TechHorizon",
    "ByteLogic",
    "CodePulse",
    "InnoSavvy",
    "DataRevolution",
    "TechBeam",
    "ByteWorks",
    "CodeNexus",
    "InnoTech",
    "DataJunction",
    "TechForge",
    "ByteCraft",
    "CodeGenius",
    "InnoWave",
    "DataSyndicate",
    "TechVision",
    "ByteMatrix",
    "CodeFrontiers",
    "InnoMind",
    "DataSavvy",
    "TechPulse",
    "ByteStorm",
    "CodeSpark",
    "InnoCraft",
    "DataImpact",
    "TechGenesis",
    "ByteStream",
    "CodeNest",
    "InnoSynergy",
    "DataBlast",
    "TechVista",
    "ByteSphere",
    "CodeLogic",
    "InnoFusion"
];
const foodBusinessNames = [
    "SavoryBiteHub",
    "FlavorFiesta",
    "TastyCraveSpot",
    "GourmetGrove",
    "ZestyPalatePlace",
    "DelishDelightsCo",
    "YumFactorHouse",
    "SatisfySpoonfuls",
    "TasteBudHaven",
    "EpicureanEatsInc",
    "MouthwaterMeals",
    "CulinaryCharms",
    "AppetiteAlchemy",
    "NourishNest",
    "FeastFusion",
    "EateriesEuphoria",
    "PalatePleasersHQ",
    "GustoGarden",
    "EdibleEnclave",
    "FlavorfulFareFirm",
    "BiteBlissBistro",
    "SavorScape",
    "TemptingTasteCo",
    "CuisineCraze",
    "YummyYieldsInc",
    "FlavorsomeFeast",
    "SatisfyStreet",
    "TasteTrove",
    "TastyTwistery",
    "DelightDineSpot",
    "GourmetGusto",
    "ZestfulZingInc",
    "DelectableDomain",
    "YumFusionFare",
    "SavorySatisfiers",
    "FlavorHaven",
    "TasteBloomCo",
    "EpicureanEdge",
    "MouthwaterMunchies",
    "CulinaryCanvas",
    "AppetiteAroma",
    "NourishNook",
    "FeastFables",
    "EateriesEcho",
    "PalatePleasures",
    "GustoGroove",
    "EdibleEssence",
    "FlavorFiesta",
    "BiteBlissBistro",
    "SavorScape"
];

console.log(foodBusinessNames.length);

function getRandomWord(obj, l) {
    const keys = Object.keys(obj);
    const RandomWord = keys[Math.floor(Math.random() * l)]
    return obj[RandomWord];

}



const agencyBtn = document.querySelector('.agency');
const selectAgency = document.querySelectorAll('.selectOpt');
const Result = document.querySelector('.result');
const foodBtn = document.querySelector('.food')
const selectFood = document.querySelectorAll('.selectFood');
const AlloptionBtn = document.querySelector('.category');
agencyBtn.addEventListener('click', () => {
    console.log("Hui!");
    agencyBtn.style.backgroundColor = "green";
    const selectAgencyBtn = document.querySelector('.selectOpt');
    selectAgencyBtn.style.display = "flex";


    selectAgency.forEach(item => item.addEventListener('click', () => {
        AlloptionBtn.style.display = "none";
        const AName = getRandomWord(techAgencyNames, 200);
        console.log(AName);
        Result.innerHTML = `Your Business name is <span  class ="bname">${AName}</span>`;
    }));
});


foodBtn.addEventListener('click', () => {
    console.log("Ok");
    foodBtn.style.backgroundColor = 'red';
    const selectFoodBtn = document.querySelector('.selectFood');
    selectFoodBtn.style.display = "flex";
    selectFood.forEach(item => item.addEventListener('click', () => {
        AlloptionBtn.style.display = "none";
        const Fname = getRandomWord(foodBusinessNames, 50);
        console.log(Fname);
        Result.innerHTML = `<p>Your Food business Name is <span class ="bname">${Fname}</span></p>`;
    }));

});
